In [10]:
class Demo:
    def test(self):
        print("test() for the class and method")
        return 
obj=Demo()
obj.test()

test() for the class and method


In [11]:
def test():
    print("test() for function")
    return
test()


test() for function


In [5]:
class Demo1:
    def fact(self,n):
        fact=1
        while(n!=0):
            fact=fact*n
            n=n-1
        return fact
p1=Demo1()
p1.fact(5)
    

120

In [11]:
class Demo2:
    def accept(self,p1,p2):
        self.p1=p1
        self.p2=p2
        return
    def display(self):
        print("a =",a)
        print("b =",b)
c1=Demo2()
c1.accept(10,20)
c1.display()


NameError: name 'a' is not defined

In [18]:
class Demo2:
    def __init__(self,p1,p2):
        self.p1=p1
        self.p2=p2
        
    def add(self):
        return self.p1+self.p2
c1= Demo2(10,20)
print(c1.add())


30


In [30]:
class Person:
    def __init__(self,name):
        self.name=name
    def getname(self):    
        return self.name
    def isemployee(self):
        return False
class employee(Person):
    def isemployee(self):
        return True
emp=Person("Manasa")
print(emp.getname(),emp.isemployee())
emp1=employee("Vasudha")
print(emp1.getname(),emp.isemployee())

Manasa False
Vasudha False


In [32]:
import numpy as np
lst=[1,2,3,4]
array=np.array(lst)
print(array)
print(array.shape)
print(array.dtype)

[1 2 3 4]
(4,)
int64


In [34]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2=np.array([(1,2),(3,4),(5,6)])
print(a2.shape)

(2, 3)
(3, 2)


In [36]:
#re-shape the given array
#numpy.reshape(arrayName,reshape,order)
a1=np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)


[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [37]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.hstack((a1,a2)))

[1 2 3 4 5 6]


In [38]:
#append data horizontally
#append data vertically
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]


In [39]:
#generate random numbers using np
a1=np.random.normal(5,0.5,10)
print(a1)

[4.72962768 4.61762849 5.40922514 4.28610364 4.92015907 5.44327961
 5.43097888 5.39650442 5.19311853 5.05916193]


In [41]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [43]:
np.zeros((2,2),dtype=np.int64)

array([[0, 0],
       [0, 0]])

In [44]:
np.ones((4,3),dtype=np.int64)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [54]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[2] = 5
np.asarray(A)[1][3] = 14
np.asarray(A)[2][0] = 16
print(A)


[[ 1  1  1  1]
 [ 1  1  1 14]
 [16  5  5  5]
 [ 1  1  1  1]]


In [4]:
import numpy as np
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [14]:
#including and slicing of array
a1=np.array(([1,2,3],[4,5,6]))
print(a1)
print("second row :",a1[1])
print("slicing row :",a1[:,1])
print("slicing last row :",a1[:,2])

[[1 2 3]
 [4 5 6]]
second row : [4 5 6]
slicing row : [2 5]
slicing last row : [3 6]


In [18]:
a1=np.array(([1,2,3],[4,5,6]))
print("row and column",a1[1,:1])

row and column [4]


In [23]:
a1=np.random.normal(5,1,10)
print(a1)
print("minimum value =",np.min(a1))
print("maximum value =",np.max(a1))
print("mean value =",np.mean(a1))
print("median value",np.median(a1))

[5.94668304 6.40222634 3.15267097 4.22934256 6.15852234 4.24094883
 4.50797996 5.49969805 4.39525896 5.77531008]
minimum value = 3.152670970212681
maximum value = 6.402226338574658
mean value = 5.0308641113036074
median value 5.003839001848311


In [28]:
c1=np.array([1,2])
c2=np.array([3,4])
np.dot(c1,c2)
np.matmul(c1,c2)


11

In [8]:
def frequencyofChar(str):
    for i in range(10):
        cnt=0
        for j in str:
            if j.isdigit():
                if(i==int(j)):
                    cnt=cnt+1
        print(cnt)
frequencyofChar("213abd456def11")        

0
3
1
1
1
1
1
0
0
0
